<?php

namespace App\Models;

use Sushi\Sushi;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Post extends Model
{
    use HasFactory, Sushi;

    protected $guarded = [];

    protected $rows = [
        ['id' => 1, 'content' => 'You ever just feel like eating a Ham sandwhich?'],
        ['id' => 2, 'content' => 'How come adults don\'t get free slices of balogne at the grocery store?'],
        ['id' => 3, 'content' => 'I wish my mom would stop using plastic wrap for my sandwiches. Ew.'],
        ['id' => 4, 'content' => 'Y\'all see that new superman lunchbox drop? I\'m sweating just thinking about it.'],
        ['id' => 5, 'content' => 'Every day is a lunchables day.'],
        ['id' => 6, 'content' => 'Mom thinks I eat my apple every day. Sucker...'],
        ['id' => 7, 'content' => 'PB&J is the GOAT of sandwiches. Fight me.'],
        ['id' => 8, 'content' => 'Why does cafeteria food always smell like wet socks?'],
        ['id' => 9, 'content' => 'I traded my cookie for a juice box. Best deal ever!'],
        ['id' => 10, 'content' => 'Caught my dad eating my leftover lunch. The betrayal is real.'],
        ['id' => 11, 'content' => 'Who else sneaks snacks into the movie theater in their lunchbox?'],
        ['id' => 12, 'content' => 'I\'m convinced the lunch lady is secretly Gordon Ramsay in disguise.'],
        ['id' => 13, 'content' => 'Why do bananas always get mushy by lunchtime? It\'s a conspiracy.'],
        ['id' => 14, 'content' => 'I\'ve mastered the art of eating chips silently during class.'],
        ['id' => 15, 'content' => 'My sandwich is always better when mom cuts it diagonally.'],
        ['id' => 16, 'content' => 'I\'m starting a petition to ban celery sticks from all lunchboxes.'],
        ['id' => 17, 'content' => 'Found a hair in my school lunch. Extra protein, I guess?'],
        ['id' => 18, 'content' => 'Why don\'t they make adult-sized Lunchables? Asking for a friend...'],
        ['id' => 19, 'content' => 'I\'m convinced my thermos is a portal to Narnia. Food never stays hot.'],
        ['id' => 20, 'content' => 'Traded my carrots for a pudding cup. I am the negotiation king!'],
        ['id' => 21, 'content' => 'Mom packed me a kale sandwich. Is this a punishment?'],
        ['id' => 22, 'content' => 'I\'ve perfected the art of making ketchup packets explode. Mwahaha!'],
        ['id' => 23, 'content' => 'Why does the "mystery meat" in the cafeteria always look so... mysterious?'],
        ['id' => 24, 'content' => 'I\'m pretty sure my lunchbox is haunted. Food keeps disappearing.'],
        ['id' => 25, 'content' => 'Started a food fight with my pb&j. Instant regret.'],
        ['id' => 26, 'content' => 'Why do we never get dessert pizza in the cafeteria? Injustice!'],
        ['id' => 27, 'content' => 'I\'m convinced the lunch lady has a secret recipe for turning cardboard into food.'],
        ['id' => 28, 'content' => 'Found a way to sneak an entire pizza into my lunchbox. I am unstoppable.'],
        ['id' => 29, 'content' => 'Why does my sandwich always taste better when I trade it with a friend?'],
        ['id' => 30, 'content' => 'I\'ve started a black market for trading pudding cups. Business is booming.'],
        ['id' => 31, 'content' => 'Mom forgot to cut the crust off. My day is ruined.'],
        ['id' => 32, 'content' => 'I\'m convinced the cafeteria uses leftover gym mats for their pizza crust.'],
        ['id' => 33, 'content' => 'Started a rumor that the meatloaf is made of actual lockers. Chaos ensued.'],
        ['id' => 34, 'content' => 'Why do parents think fruit snacks are a suitable replacement for actual fruit?'],
        ['id' => 35, 'content' => 'I\'ve developed a sixth sense for detecting when someone has Oreos in their lunch.'],
        ['id' => 36, 'content' => 'Trying to convince my friends that my veggie sticks are actually alien fingers.'],
        ['id' => 37, 'content' => 'Why does the milk always taste like the carton? It\'s a dairy conspiracy.'],
        ['id' => 38, 'content' => 'I\'ve mastered the art of eating a messy sloppy joe without getting any on my shirt.'],
        ['id' => 39, 'content' => 'Started a petition to replace all water fountains with chocolate milk. Who\'s with me?'],
        ['id' => 40, 'content' => 'Why do bananas bruise so easily in my lunchbox? They\'re such drama queens.'],
        ['id' => 41, 'content' => 'I\'m convinced my sandwich grows mold the minute I put it in my lunchbox.'],
        ['id' => 42, 'content' => 'Trading lunches is like the stock market. Gotta know when to hold \'em, know when to fold \'em.'],
        ['id' => 43, 'content' => 'Why does the cafeteria always run out of the good stuff right before my lunch period?'],
        ['id' => 44, 'content' => 'I\'ve started timing how long it takes for my apple to turn brown. New personal record!'],
        ['id' => 45, 'content' => 'Mom packed me sushi. The whole lunch table thinks I\'m eating bait.'],
        ['id' => 46, 'content' => 'I\'m pretty sure the lunch lady can read minds. She always knows when I\'m lying about allergies.'],
        ['id' => 47, 'content' => 'Why do we never get breakfast for lunch? I demand pancakes at noon!'],
        ['id' => 48, 'content' => 'I\'ve developed a highly scientific method for separating Oreo cookies. Patent pending.'],
        ['id' => 49, 'content' => 'Started a rumor that the blue Jell-O gives you superpowers. Mass hysteria ensued.'],
        ['id' => 50, 'content' => 'Why does my sandwich always end up squished at the bottom of my backpack?'],
        ['id' => 51, 'content' => 'I\'ve perfected the art of sneaking food into the library. Ninja skills level: expert.'],
        ['id' => 52, 'content' => 'Tried to convince my friend that my green beans were actually alien antennae. No luck.'],
        ['id' => 53, 'content' => 'Why does the cafeteria think that putting raisins in anything makes it healthier?'],
        ['id' => 54, 'content' => 'I\'ve started a underground network for trading Pokemon cards during lunch. Business is booming.'],
        ['id' => 55, 'content' => 'Mom packed me a thermos of soup. Pretty sure it\'ll still be hot next week.'],
        ['id' => 56, 'content' => 'I\'m convinced the lunch lady has a secret portal to another dimension in the kitchen.'],
        ['id' => 57, 'content' => 'Why do oranges always squirt you in the eye when you try to peel them? It\'s a citrus assault!'],
        ['id' => 58, 'content' => 'I\'ve developed a foolproof system for sneaking extra desserts. The lunch lady suspects nothing.'],
        ['id' => 59, 'content' => 'Started a betting pool on what the mystery meat actually is. Taking all bets!'],
        ['id' => 60, 'content' => 'Why does my sandwich always taste like my eraser by the end of the day?'],
        ['id' => 61, 'content' => 'I\'ve invented a new game: Guess That Smell. Cafeteria edition. No one wants to play...'],
        ['id' => 62, 'content' => 'Tried to trade my brussels sprouts for literally anything. No takers.'],
        ['id' => 63, 'content' => 'Why does the school think a single chicken nugget counts as a serving of protein?'],
        ['id' => 64, 'content' => 'I\'ve started a secret society for kids with cool lunchboxes. We meet at the monkey bars.'],
        ['id' => 65, 'content' => 'Mom packed me a note with my lunch. Cute, but can I eat it?'],
        ['id' => 66, 'content' => 'I\'m convinced the vending machine is sentient and purposely eats my dollars.'],
        ['id' => 67, 'content' => 'Why does the cafeteria think that mixing corn with everything makes it gourmet?'],
        ['id' => 68, 'content' => 'I\'ve mastered the art of opening my chip bag silently during a test. Ninja level: 100.'],
        ['id' => 69, 'content' => 'Started a rumor that the lunch lady\'s hairnet is actually a mind-control device. Mass panic ensued.'],
        ['id' => 70, 'content' => 'Why does my banana always end up looking like it went through a war by lunchtime?'],
        ['id' => 71, 'content' => 'I\'ve developed a complex trading system based on the perceived value of various snack items.'],
        ['id' => 72, 'content' => 'Tried to convince my tablemates that my peas were actually tiny alien eggs. They\'re not buying it.'],
        ['id' => 73, 'content' => 'Why does the school think that pizza with a side of pizza is a balanced meal?'],
        ['id' => 74, 'content' => 'I\'ve started a lunchtime debate club. Today\'s topic: Is a hot dog a sandwich?'],
        ['id' => 75, 'content' => 'Mom packed me leftover brussel sprouts. Is this grounds for emancipation?'],
        ['id' => 76, 'content' => 'I\'m convinced the lunch lady has a secret recipe book hidden in the freezer.'],
        ['id' => 77, 'content' => 'Why do apples always sound so loud when you bite into them during a quiet moment?'],
        ['id' => 78, 'content' => 'I\'ve created a detailed map of the cafeteria, marking all the prime sitting locations.'],
        ['id' => 79, 'content' => 'Started a petition to rename the mystery meat to "Surprise Protein". Who\'s with me?'],
        ['id' => 80, 'content' => 'Why does my juice box always explode when I try to put the straw in? It\'s a juice conspiracy.'],
        ['id' => 81, 'content' => 'I\'ve developed a code language based on the arrangement of food on my tray. Spies everywhere!'],
        ['id' => 82, 'content' => 'Tried to use my banana as a phone during lunch. Got some weird looks.'],
        ['id' => 83, 'content' => 'Why does the cafeteria think that putting a single cherry tomato on a salad makes it fancy?'],
        ['id' => 84, 'content' => 'I\'ve started a lunchtime yoga class using cafeteria trays as yoga mats. Namaste!'],
        ['id' => 85, 'content' => 'Mom packed me a turmeric sandwich. My mouth looks like I ate a highlighter.'],
        ['id' => 86, 'content' => 'I\'m convinced the lunch lady is secretly a gourmet chef moonlighting in our cafeteria.'],
        ['id' => 87, 'content' => 'Why do the big kids always get to cut in line? I demand lunch equality!'],
        ['id' => 88, 'content' => 'I\'ve perfected the art of making a sandwich tower. Engineering degree, here I come!'],
        ['id' => 89, 'content' => 'Started a rumor that the fish sticks are actually mermaid fingers. Chaos in the cafeteria!'],
        ['id' => 90, 'content' => 'Why does my dessert always disappear before I get to it? I suspect lunch gnomes.'],
        ['id' => 91, 'content' => 'I\'ve started a lucrative business selling "lunch insurance". Protection from sandwich thieves!'],
        ['id' => 92, 'content' => 'Tried to use my carrot sticks as chopsticks. Modern problems require modern solutions.'],
        ['id' => 93, 'content' => 'Why does the cafeteria think that calling it a "Nutrition Center" makes the food taste better?'],
        ['id' => 94, 'content' => 'I\'ve developed a complex algorithm for predicting the daily special. 60% of the time, it works every time.'],
        ['id' => 95, 'content' => 'Mom packed me a sandwich with the crust cut off. I\'m not a baby, I\'m eight and three quarters!'],
        ['id' => 96, 'content' => 'I\'m convinced the lunch lady has a sixth sense for knowing who\'s going to ask for seconds.'],
        ['id' => 97, 'content' => 'Why do we never get pizza day and ice cream day on the same day? It\'s a missed opportunity!'],
        ['id' => 98, 'content' => 'I\'ve started a lunchtime radio show using an empty juice carton as a microphone. Ratings are soaring!'],
        ['id' => 99, 'content' => 'Started a rumor that the mashed potatoes are actually moon rocks. Science class is investigating.'],
        ['id' => 100, 'content' => 'Why does my lunchbox always smell like a weird combination of banana and gym socks?'],
        ['id' => 101, 'content' => 'I\'ve developed a sophisticated bartering system using cookies as currency. The lunch economy is booming!'],
        ['id' => 102, 'content' => 'Tried to convince my friends that my broccoli was a miniature forest. They weren\'t impressed.'],
        ['id' => 103, 'content' => 'Why does the cafeteria think that adding a sprig of parsley makes everything gourmet?'],
        ['id' => 104, 'content' => 'I\'ve started a lunchtime detective agency. First case: The Case of the Missing Pudding Cup.'],
        ['id' => 105, 'content' => 'Mom packed me a glitter sandwich. I\'m sparkling, but at what cost?'],
        ['id' => 106, 'content' => 'I\'m convinced the vending machine has a personal vendetta against me. It ate my dollar... again.'],
        ['id' => 107, 'content' => 'Why do we never get to vote on the lunch menu? I demand lunch democracy!'],
        ['id' => 108, 'content' => 'I\'ve mastered the art of building the perfect sandwich stack. It\'s basically lunch Jenga.'],
    ];
}
